apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-bellyback
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-belly
            image: agriuseatstweets/bellyback
            resources:
              requests:
                memory: "372Mi"
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/usr/share/keys/key.json"
              - name: BELLY_QUEUE
                value: "kafka"
              - name: KAFKA_BROKERS
                value: "kafka:9092"
              - name: BELLY_LOCATION
                value: "spain-tweets-backup"
              - name: BELLY_SIZE
                value: "30"
              - name: LS_JAVA_OPTS
                value: "-Xmx1024m -Xms256m"
            volumeMounts:
              - name: keys
                mountPath: /usr/share/keys
                readOnly: true
          volumes:
            - name: keys
              secret:
                secretName: agrius-bellyback-keys
