apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-belly
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-belly
            image: nandanrao/agrius-belly
            resources:
              requests:
                memory: "372Mi"
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/usr/share/keys/key.json"
              - name: GOOGLE_PROJECT_ID
                value: "toixotoixo"
              - name: GOOGLE_PUBSUB_SUBSCRIPTION
                value: "agrius-india-belly"
              - name: BELLY_LOCATION
                value: "agrius-tweethouse"
              - name: BELLY_SIZE
                value: "20"
              - name: LS_JAVA_OPTS
                value: "-Xmx1024m -Xms256m"
            volumeMounts:
              - name: keys
                mountPath: /usr/share/keys
                readOnly: true
          volumes:
            - name: keys
              secret:
                secretName: agrius-belly-keys
